# /ngs/RDI/SCRIPTS/az.reporting

genomes:
  hg38:
    seq: /ngs/reference_data/genomes/Hsapiens/hg38/seq/hg38.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg38/bwa/hg38.fa

    dbsnp:   /ngs/reference_data/genomes/Hsapiens/hg38/variation/dbSNP_latest.vcf.gz
    clinvar: /ngs/reference_data/genomes/Hsapiens/hg38/variation/ClinVar_latest.vcf.gz
    cosmic:  /ngs/reference_data/genomes/Hsapiens/hg38/variation/CosmicCodingMuts_latest.vcf.gz
    snpeff:
      reference: hg38
    snpeff_transcripts:       /ngs/reference_data/genomes/Hsapiens/hg38/canonical_transcripts.txt

    az_exome: /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exome-AZ.bed

    features:                 /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg38.canon.bed
    bed_annotation_features:  /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exons/RefSeq/RefSeq.all_features.hg38.bed
    cds:                      /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exons/RefSeq/RefSeq_CDS.hg38.bed

    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg38/variation/dbSNP_multi_mafs_latest.txt

    all_transcripts:              /ngs/reference_data/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf

    tricky_regions:               /ngs/reference_data/genomes/Hsapiens/hg38/bed/tricky_regions

    circos_cytoband: /ngs/reference_data/genomes/Hsapiens/hg38/circos/cytoband.txt.gz

  hg38-noalt:
    seq: /ngs/reference_data/genomes/Hsapiens/hg38/seq/hg38.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg38/bwa/hg38.fa

    dbsnp:   /ngs/reference_data/genomes/Hsapiens/hg38/variation/dbSNP_latest.vcf.gz
    clinvar: /ngs/reference_data/genomes/Hsapiens/hg38/variation/ClinVar_latest.vcf.gz
    cosmic:  /ngs/reference_data/genomes/Hsapiens/hg38/variation/CosmicCodingMuts_latest.vcf.gz
    snpeff:
      reference: hg38
    snpeff_transcripts:       /ngs/reference_data/genomes/Hsapiens/hg38/canonical_transcripts.txt

    az_exome: /ngs/reference_data/genomes/Hsapiens/hg38/bed/Exome-AZ.bed

    features:                 /ngs/reference_data/genomes/Hsapiens/hg38-noalt/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg38-noalt.canon.bed
    bed_annotation_features:  /ngs/reference_data/genomes/Hsapiens/hg38-noalt/bed/Exons/RefSeq/RefSeq.all_features.hg38-noalt.bed
    cds:                      /ngs/reference_data/genomes/Hsapiens/hg38-noalt/bed/Exons/RefSeq/RefSeq_CDS.hg38-noalt.bed

    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg38-noalt/variation/dbSNP_multi_mafs_latest.txt

    all_transcripts:              /ngs/reference_data/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf

    tricky_regions:               /ngs/reference_data/genomes/Hsapiens/hg38-noalt/bed/tricky_regions

    circos_cytoband: /ngs/reference_data/genomes/Hsapiens/hg38/circos/cytoband.txt.gz

  hg19:
    seq: /ngs/reference_data/genomes/Hsapiens/hg19/seq/hg19.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg19/bwa/hg19.fa

    dbsnp:       /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_latest.vcf.gz
    clinvar:     /ngs/reference_data/genomes/Hsapiens/hg19/variation/ClinVar_latest.vcf.gz
    cosmic:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/CosmicCodingMuts_latest.vcf.gz
    oncomine:    /ngs/reference_data/genomes/Hsapiens/hg19/variation/oncomine/oncomine_latest.vcf.gz
    dbnsfp:      /ngs/reference_data/genomes/Hsapiens/hg19/dbNSF/dbNSFP_latest.txt.gz

    snpeff:
      reference: hg19
    snpeff_transcripts:       /ngs/reference_data/genomes/Hsapiens/hg19/canonical_transcripts.txt

    az_exome: /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exome-AZ.bed

    features:                 /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg19.canon.bed
    bed_annotation_features:  /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq.all_features.hg19.bed
    cds:                      /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq_CDS.hg19.bed

    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_multi_mafs_latest.txt

    all_transcripts:              /ngs/reference_data/genomes/Hsapiens/hg19/rnaseq/ref-transcripts.gtf

    tricky_regions: /ngs/reference_data/genomes/Hsapiens/hg19/bed/tricky_regions

  hg19-chr20:
    seq: /ngs/reference_data/genomes/Hsapiens/hg19/seq/hg19.fa
    bwa: /ngs/reference_data/genomes/Hsapiens/hg19/bwa/hg19.fa

    dbsnp:       /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_latest.vcf.gz
    clinvar:     /ngs/reference_data/genomes/Hsapiens/hg19/variation/ClinVar_latest.vcf.gz
    cosmic:      /ngs/reference_data/genomes/Hsapiens/hg19/variation/CosmicCodingMuts_latest.vcf.gz
    oncomine:    /ngs/reference_data/genomes/Hsapiens/hg19/variation/oncomine/oncomine_latest.vcf.gz
    dbnsfp:      /ngs/reference_data/genomes/Hsapiens/hg19/dbNSF/dbNSFP_latest.txt.gz

    snpeff:
      reference: hg19
    snpeff_transcripts:       /ngs/reference_data/genomes/Hsapiens/hg19/canonical_transcripts.txt

    az_exome: /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exome-AZ.bed

    features:                 /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq_CDS_miRNA.all_features.hg19-chr20.canon.bed
    bed_annotation_features:  /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq.all_features.hg19-chr20.bed
    cds:                      /ngs/reference_data/genomes/Hsapiens/hg19/bed/Exons/RefSeq/RefSeq_CDS.hg19-chr20.bed

    dbsnp_multi_mafs:             /ngs/reference_data/genomes/Hsapiens/hg19/variation/dbSNP_multi_mafs_latest.txt

    all_transcripts:              /ngs/reference_data/genomes/Hsapiens/hg19/rnaseq/ref-transcripts.gtf

    tricky_regions: /ngs/reference_data/genomes/Hsapiens/hg19/bed/tricky_regions

queue: ngs.q
scheduler: sge
resources: [pename=smp]
priority: 0

smtp_host: 'localhost'
